### ISSUE TITLE
로컬 함수의 변수와 로컬함수 내에서 쓰인 lambda가 포획한 로컬 변수의 생명주기는 다르다

### ISSUE THREAD

**Issue by parksjin01** [start-with-kotlin/kotlin#5]
Kotlin in Action을 스터디하던 중에 [람다의 변수 포획 중 비동기로 로컬 변수를 활용할 때의 이슈를 다루는 부분](https://github.com/start-with-kotlin/kotlin/blob/master/Kotlin%20in%20Action/chapter05/chapter05.md#%EB%9E%8C%EB%8B%A4%EB%A5%BC-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%ED%95%B8%EB%93%A4%EB%9F%AC%EB%82%98-%EB%8B%A4%EB%A5%B8-%EB%B9%84%EB%8F%99%EA%B8%B0%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%8B%A4%ED%96%89%EB%90%98%EB%8A%94-%EC%BD%94%EB%93%9C%EB%A1%9C-%ED%99%9C%EC%9A%A9%ED%95%98%EB%8A%94-%EA%B2%BD%EC%9A%B0-%ED%95%A8%EC%88%98-%ED%98%B8%EC%B6%9C%EC%9D%B4-%EB%81%9D%EB%82%9C-%EB%8B%A4%EC%9D%8C%EC%97%90-%EB%A1%9C%EC%BB%AC-%EB%B3%80%EC%88%98%EA%B0%80-%EB%B3%80%EA%B2%BD%EB%90%A0-%EC%88%98%EB%8F%84-%EC%9E%88%EB%8B%A4)에 관한 예제를 이해하기 위해 해당 이슈를 생성하였다.

Kotlin in Action에서 나온 아래 예제 코드로는 이해에 어려움이 있어 직접 예제 코드를 만들어 실험해보았다.
```kotlin
fun tryToCountButtonClicks(button: Button): Int {
    var clicks = 0
    button.onClick { clicks++ }
    return clicks
}
```

**Comment by kjw217** [comment]
로컬 함수 내에서 선언된 변수의 경우에는 그 생명주기가 **기본적으로는 그 변수를 선언한 로컬 함수와 같다.**
하지만 로컬 함수 내에 있는 **람다에 의해 포획된 로컬 변수**는 그 생명주기를 람다와 함께 한다.
다음의 예제 코드를 통해 확인해보자.

```kotlin
fun practiceClosure(): Pair<Int, () -> Int> {
    var localValue = 0                   // (1)
    val lamb = {localValue++}      // (2)
    return Pair(localValue, lamb)
}

fun main(args: Array<String>) {
    var (localValue, lamb) = practiceClosure()       // (3)
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
}

//>> (0, 0)
//>> (0, 1)
//>> (0, 2)
//>> (0, 3)
```

위 예제 코드에서 `practiceClosure()` 최상위 함수는 지속적으로 새롭게 호출된다. 
- 따라서 `practiceClosure()` 함수의 로컬 변수인 `localValue`는 매번 (1)에 의해 0으로 초기화 되어 반환된다. 
- 하지만 `lamb()` 람다의 경우 (3)에서 `practiceClosure()`의 로컬 변수인 `localValue`를 포획했다. 
- 그 후에 `lamb()`를 호출할 때마다 (3)에서 포획한 변수를 증가시켜 출력하는 것을 확인할 수 있었다.
